version: "3"

volumes: 
  databases:

services:
  products-master:
    image: mysql:8.0.36
    container_name: products-master 
    volumes:
      - databases:/data/db_master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products 
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    ports:
      - "3307:3306"

  products-slave:
    image: mysql:8.0.36
    container_name: products-slave
    depends_on:
      - products-master
    volumes:
      - databases:/data/db_slave
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_USER: slave
      MYSQL_PASSWORD: slave
    ports:
      - "3308:3306"